// ============================================================
// Kitchen Mama Operation System — Apps Script (modularized source mirror)
// 14_fc_write_handlers.gs — FC Summary write path (Phase 1)
//   Special Events (fc_special_events) + Target % Rules (fc_target_rules)
// NOTE: All .gs files in this folder share ONE global scope in the Apps
//       Script project. Copy them into the project TOGETHER and REDEPLOY. No imports.
//
// Scope (Phase 1): read/write for fc_special_events + fc_target_rules ONLY.
//   Does NOT touch fc_regular_forecast (Edit Base FC / Add SKU / Import are Phase 2 / existing).
//   Tabs are auto-created with the documented header row on first WRITE (missing tab is [] on read).
//   Handlers: handleUpsertFcSpecialEvent_ / handleDeleteFcSpecialEvent_
//             handleUpsertFcTargetRule_   / handleDeleteFcTargetRule_
// ============================================================

// F1-7N-FC-1B-E3-R4-A2-R1-R6-R7-R12 -- 14_ BECOMES A MANIFEST OWNER, and it should have been one before now.
// This round gave the Target Rule upsert a real identity: it resolves an existing rule by the canonical
// business key (year|company|country|marketplace|scope_type|scope_id), refuses a duplicate and refuses an
// id that points at a different site, takes a script lock, and writes the row in ONE range call.
// An OLD 14_ answers the SAME action with the SAME payload and returns SUCCESS: it keys on target_rule_id
// alone, so the FC modal -- which sends no id -- APPENDS A DUPLICATE ROW on every re-save, and two
// concurrent creates both append. Nothing about that is visible from outside: no action is missing, no
// handler is undefined, no response changes shape. It is the precise case the module manifest was built for.
//
// The SYMBOL is new in this round, so a copy of 14_ older than this one reports ABSENT rather than stale.
// That is the stronger signal, and it is why the value is not backdated to the round the file first shipped.
// R13 — THE STAMP MOVES BECAUSE THIS FILE CHANGED, and the change is a WRITE CONTRACT change, which
// is the kind this stamp exists for. handleUpsertFcTargetRule_ now demands expected_row_version on any
// update, refuses a version-less body over an existing row, short-circuits an unchanged save to zero
// writes, and returns the complete saved row as a receipt.
//
// An OLD 14_ beside the new page is the dangerous pairing, and it is silent: the page would send
// expected_row_version and the old handler would IGNORE it — accepting every stale write it was added
// to refuse, while returning success. Only a declared build separates those two deployments.
var FCW_BUILD_VERSION_ = 'F1-7N-FC-1B-E3-R4-A2-R1-R6-R7-R18';

// fc_special_events header. event_name / event_month / fc_qty are the task-defined columns;
// event_period + year are additional UI-continuity columns (FC Summary Event table shows/filters them).
// 2026-07-22 (ADDITIVE): campaign_id / campaign_sku_line_id link each event forecast back to its
//   parent campaign + campaign line (Special Event Builder writes campaigns → campaign_sku_lines →
//   fc_special_events); marketplace_id is the canonical marketplace identity (company-safe, since the
//   same marketplace NAME can belong to two companies); event_start_date / event_end_date are the
//   linked event-period snapshot (event_period kept as legacy/display; event_month = allocation month).
//   New columns are appended to an EXISTING sheet's header row by fcWriteEnsureColumns_ — never
//   renaming or dropping a live column (migration-safe, no redeploy assumption baked in).
// PK aligned to the CANONICAL name `event_fc_id` (FC_SUMMARY_SPEC §3.1) — 2026-07-22. The prior header
// used `event_id`, which left the real `event_fc_id` PK column BLANK on sheets whose PK is `event_fc_id`
// (fcWriteEnsureColumns_ appended a stray `event_id` column instead). event_fc_id is generated by the
// backend (see handleUpsertFcSpecialEvent_ / fcSpecialEventUpsert_); a legacy `event_id` column, if any,
// is left untouched (never dropped) but no longer written.
var FC_SPECIAL_EVENTS_HEADERS_ = [
  'event_fc_id', 'campaign_id', 'campaign_sku_line_id',
  'company', 'country', 'marketplace', 'marketplace_id', 'scope_type', 'scope_id',
  'sku', 'series', 'category', 'event_name',
  'event_period', 'event_start_date', 'event_end_date', 'event_month', 'year', 'fc_qty',
  'note', 'created_by', 'created_at', 'updated_by', 'updated_at'
];

// fc_target_rules header. scope_type / scope_id + jan_pct..dec_pct are the task-defined columns;
// year / category / series / sku are additional UI-continuity columns (Target table shows them and
// the effective-rule resolver matches on year + scope value).
var FC_TARGET_RULES_HEADERS_ = [
  'target_rule_id', 'company', 'country', 'marketplace', 'scope_type', 'scope_id',
  'year', 'category', 'series', 'sku', 'target_percentage',
  'jan_pct', 'feb_pct', 'mar_pct', 'apr_pct', 'may_pct', 'jun_pct',
  'jul_pct', 'aug_pct', 'sep_pct', 'oct_pct', 'nov_pct', 'dec_pct',
  'note', 'created_by', 'created_at', 'updated_by', 'updated_at'
];

// ============================================================================================================
// FC-SUMMARY-R2B-A — TWO SCHEMA MODES, AND WHY THE SECOND ONE EXISTS.
//
// `ORDERED` is the S0.5 gate: the canonical header array must be the live header row's leading prefix. It is
// the DEFAULT and it is the only mode a table can get without being named below.
//
// `REQUIRED_COLUMNS_BY_NAME` validates the same facts EXCEPT position: wrong spreadsheet, missing tab, blank
// header, duplicate header and missing required column all still fail closed with the same tokens. Only the
// ORDER requirement is dropped.
//
// It exists because the ordered gate was refusing writes it had no reason to refuse. The live `campaigns`,
// `campaign_sku_lines` and `fc_special_events` header rows contain every required column, unique and non-blank,
// but NOT in the constant's order — because this system's OWN additive migration put them where they are:
// `fcWriteEnsureColumns_` used to append a missing header at the right edge, so `company`, `event_flag`,
// `created_by`, `updated_by` sit at the end of `campaigns` instead of at indexes 1, 8, 21, 23. The S0.5 round
// then made that same helper validate-only and added an ORDER check that the earlier behaviour can never
// satisfy. The result was `PRODUCTION_SAFETY:HEADER_ORDER_MISMATCH [campaigns]` on every Special Event save.
//
// Dropping the order check is SAFE for exactly these tables and no others, because every write in this file and
// in 20_ resolves the LIVE header by NAME — `fcWriteAppendByHeader_` builds its row from the live header row and
// `fcWriteUpsert_`'s setCell uses `s.col(name)`. There is no positional write to break. That is the same
// reasoning, and the same resolution, already applied to `shipping_plan_lines` in 11_.
//
// SCOPE IS DELIBERATELY NARROW. `fcWriteEnsureSheet_` is shared by fourteen tables. A table gets the relaxed
// mode only if it is named here AND its call site asks for it — two independent conditions, so neither a stray
// flag nor a stray list entry can relax a table on its own. Anything else silently keeps ORDERED, which is the
// STRICTER gate: falling back can only ever refuse more, never less.
// ============================================================================================================
var FC_SCHEMA_ORDERED_ = 'ORDERED';
var FC_SCHEMA_BY_NAME_ = 'REQUIRED_COLUMNS_BY_NAME';

// The ONLY tables approved for REQUIRED_COLUMNS_BY_NAME.
//
// `fc_target_rules` was excluded in R2B-A because its live header row had never been observed — the table has
// no data rows, so every deployed read returns [] and says nothing about row 1. Row 1 has now been supplied,
// and it is worse than merely reordered: three REQUIRED columns are genuinely absent (`scope_type`, `scope_id`,
// `target_percentage`), which is why the live refusal was HEADER_MISSING and not HEADER_ORDER_MISMATCH.
//
// Order tolerance cannot conjure a column that is not there, so membership here does NOT by itself unblock the
// write: `prodRequireColumns_` still refuses with MISSING_REQUIRED_HEADER until the additive migration in
// TEMP_migrate_fc_target_rules_header_r2ba2.gs has actually appended those three columns. That ordering is
// deliberate — the table can be listed safely BEFORE the migration runs, because the second lock is what holds
// it shut, and the refusal it produces names the real cause instead of blaming column order.
var FC_SCHEMA_BY_NAME_TABLES_ = ['campaigns', 'campaign_sku_lines', 'fc_special_events', 'fc_target_rules'];

function fcWriteSchemaByNameApproved_(name, mode) {
  if (mode !== FC_SCHEMA_BY_NAME_) return false;              // no opt-in → ORDERED
  for (var i = 0; i < FC_SCHEMA_BY_NAME_TABLES_.length; i++) {
    if (FC_SCHEMA_BY_NAME_TABLES_[i] === name) return true;   // opt-in AND approved
  }
  return false;                                               // opt-in on an unapproved table → still ORDERED
}

function fcWriteTimestamp_() {
  return Utilities.formatDate(new Date(), Session.getScriptTimeZone(), 'yyyy-MM-dd HH:mm:ss');
}

/** Get (or create with the documented header row) an FC write tab. */
// Production Safety Round S0.5 (RULE S0-2/S0-5): VALIDATE-ONLY (no auto-create / no Header write). Delegates to the
// shared safety adapter (29_); create is migration-only (prodMigrateCreateSheet_), unreachable from Runtime.
function fcWriteEnsureSheet_(ss, name, headers, mode) {
  // FC-SUMMARY-R2B-A — approved table + explicit opt-in: validate everything except column ORDER.
  // prodRequireSheet_(ss, name, []) still enforces the spreadsheet target, the tab, blank headers and
  // duplicate headers; prodRequireColumns_ still enforces every required column. Nothing is relaxed
  // beyond position, and no sheet, header or column is created, renamed, moved or appended.
  if (fcWriteSchemaByNameApproved_(name, mode)) {
    var byName = prodRequireSheet_(ss, name, []);
    prodRequireColumns_(byName, (headers || []).filter(function (h) { return !!h; }));
    return byName;
  }
  return prodRequireSheet_(ss, name, headers);
}

/**
 * Production Safety Round S0.5 (RULE S0-2): VALIDATE-ONLY. Normal Runtime no longer appends missing Header columns
 * on write — any missing REQUIRED column fails closed (MISSING_REQUIRED_HEADER) with ZERO mutation. Additive column
 * migration is migration-only (prodMigrateAppendColumns_ in 29_). Returns 0 (validate passed → nothing appended).
 */
function fcWriteEnsureColumns_(sheet, headers) {
  prodRequireColumns_(sheet, (headers || []).filter(function (h) { return !!h; }));
  return 0;
}

/** Read a sheet as { headers, rows(values), col(name) }. */
function fcWriteReadSheet_(sheet) {
  var data = sheet.getDataRange().getValues();
  var headers = (data[0] || []).map(function (h) { return String(h).trim(); });
  return {
    headers: headers,
    rows: data,
    col: function (n) { return headers.indexOf(n); }
  };
}

/** Append a row using the sheet's existing header row (writes only known columns). */
function fcWriteAppendByHeader_(sheet, obj) {
  var lastCol = sheet.getLastColumn();
  var headers = sheet.getRange(1, 1, 1, lastCol).getValues()[0].map(function (h) { return String(h).trim(); });
  var row = new Array(headers.length).fill('');
  for (var i = 0; i < headers.length; i++) {
    if (obj.hasOwnProperty(headers[i]) && obj[headers[i]] !== undefined && obj[headers[i]] !== null) {
      row[i] = obj[headers[i]];
    }
  }
  sheet.appendRow(row);
}

/**
 * Generic header-based upsert by id column. Updates the matching row's known columns (only keys
 * present in body that are also sheet headers), else appends a new row. Stamps created/updated meta.
 * Returns { id, created }.
 */
function fcWriteUpsert_(ss, sheetName, headers, idCol, idValue, body, actor, mode) {
  // FC-SUMMARY-R2B-A — `mode` is threaded, never defaulted to the relaxed value. A caller that omits it
  // gets ORDERED, which is what `fc_target_rules` (14_) still gets today.
  var sheet = fcWriteEnsureSheet_(ss, sheetName, headers, mode);
  fcWriteEnsureColumns_(sheet, headers);   // ADDITIVE: back-fill any new columns onto a pre-existing sheet
  var s = fcWriteReadSheet_(sheet);
  var now = fcWriteTimestamp_();
  var idColIdx = s.col(idCol);
  if (idColIdx === -1) throw new Error(idCol + ' column not found in ' + sheetName);

  // Locate existing row by id (when an id was supplied).
  var targetRow = -1;
  if (idValue) {
    for (var i = 1; i < s.rows.length; i++) {
      if (String(s.rows[i][idColIdx]).trim() === String(idValue).trim()) { targetRow = i + 1; break; }
    }
  }

  if (targetRow === -1) {
    // Create new.
    var newId = idValue || (sheetName + '-' + Utilities.getUuid().substring(0, 12).toUpperCase());
    var createObj = {};
    createObj[idCol] = newId;
    headers.forEach(function (h) {
      if (body.hasOwnProperty(h) && h !== idCol) createObj[h] = body[h];
    });
    createObj.created_by = actor;
    createObj.created_at = now;
    createObj.updated_by = actor;
    createObj.updated_at = now;
    fcWriteAppendByHeader_(sheet, createObj);
    return { id: newId, created: true };
  }

  // Update existing: only write columns present in body that are real headers (never the id / created_*).
  function setCell(name, value) { var c = s.col(name); if (c !== -1) sheet.getRange(targetRow, c + 1).setValue(value); }
  headers.forEach(function (h) {
    if (h === idCol || h === 'created_by' || h === 'created_at') return;
    if (body.hasOwnProperty(h)) setCell(h, body[h]);
  });
  setCell('updated_by', actor);
  setCell('updated_at', now);
  return { id: String(idValue).trim(), created: false };
}

/**
 * Generic hard-delete by id column. Returns { id, deleted }.
 *
 * FC-SUMMARY-R2B-A2 — THIS WAS THE ONE WRITE IN THIS FILE THAT REACHED A STRUCTURAL MUTATION WITH NO SCHEMA
 * VALIDATION AT ALL. It resolved the sheet with a bare `getSheetByName`, took whatever header row it found,
 * and called `deleteRow` — so a drifted, blank-headed or duplicate-headed sheet would have had a row removed
 * by position on the strength of an index resolved from a header nobody had checked. Deleting the wrong row is
 * not recoverable by a retry, which makes an ungated delete strictly worse than an ungated append.
 *
 * It now passes through the SAME gate as every other write here, with the same two locks. A caller that omits
 * `mode` still gets ORDERED; a caller that omits `headers` gets presence validation against an empty required
 * set, which still enforces the spreadsheet target, the tab, blank headers and duplicate headers.
 *
 * An ABSENT TAB stays the soft `sheet_not_found` it has always been, because a delete against a table that does
 * not exist has already achieved what it was asked to do and there is nothing to protect. Every other schema
 * fault throws, and `not_found` remains a zero-write outcome.
 */
function fcWriteDelete_(ss, sheetName, idCol, idValue, headers, mode) {
  if (!ss.getSheetByName(sheetName)) return { id: idValue, deleted: false, reason: 'sheet_not_found' };
  var sheet = fcWriteEnsureSheet_(ss, sheetName, headers || [], mode);
  if (headers && headers.length) fcWriteEnsureColumns_(sheet, headers);
  var s = fcWriteReadSheet_(sheet);
  var idColIdx = s.col(idCol);
  if (idColIdx === -1) return { id: idValue, deleted: false, reason: 'id_column_missing' };
  for (var i = 1; i < s.rows.length; i++) {
    if (String(s.rows[i][idColIdx]).trim() === String(idValue).trim()) {
      sheet.deleteRow(i + 1);
      return { id: idValue, deleted: true };
    }
  }
  return { id: idValue, deleted: false, reason: 'not_found' };
}

// ---- fc_special_events ----

// Uppercase-trim compare helper for fc_special_events business-key matching.
function fcEvtUp_(v) { return String(v == null ? '' : v).trim().toUpperCase(); }

// FC-SUMMARY-R2B-A3-R9 §3 — ONE EVENT FLAG, ONE TARGET YEAR, ONE SCOPED SKU = ONE EVENT.
//
// The product rule frozen in FC_SUMMARY_SPEC.md §10.1: a different start/end date does NOT authorise a
// second logical event for the same scoped SKU. The window belongs to the CAMPAIGN's identity, not the
// event's, so two events differing only by window are one event stored twice.
//
// The client preflights this, and the client cannot be the authority. A stale read model, a second tab,
// two concurrent New Event saves, a direct API caller and a replayed request all compose a create the
// browser believes is legitimate. The existing business-key resolution cannot catch them either: it keys
// on campaign_id + line (or campaign_id + sku + month + year), so an event authored under a DIFFERENT
// campaign - which is exactly what a different window produces - resolves to no row and appends.
//
// This is deliberately a scan and not a schema constraint. fc_special_events has no unique index and
// adding one is a migration; under the script lock the campaign writer already holds for stage 1, and
// with this read happening inside the same invocation as the append, the remaining race is two requests
// that both pass the scan before either appends. That window is real and is reported rather than hidden:
// it is narrower than the one it replaces (which had no check at all) and closing it fully requires the
// migration this round is not authorised to make.
var FC_SE_UNIQUENESS_FIELDS_ = ['company', 'country', 'marketplace', 'sku', 'event_name', 'year'];
function fcSeUniquenessKey_(get) {
  return FC_SE_UNIQUENESS_FIELDS_.map(function (fld) { return fcEvtUp_(get(fld)); }).join('|');
}
// Returns the conflicting row {event_fc_id, event_start_date, event_end_date} or null. `selfRow` is the
// 1-based sheet row this write already owns, so an UPDATE never conflicts with itself.
function fcSeUniquenessConflict_(s, body, selfRow) {
  var iId = s.col('event_fc_id');
  var want = fcSeUniquenessKey_(function (fld) { return body[fld]; });
  // An incomplete key cannot identify anything, so it cannot prove a conflict either.
  if (want.split('|').some(function (p) { return p === ''; })) return null;
  for (var i = 1; i < s.rows.length; i++) {
    var rowNo = i + 1;
    if (selfRow > 0 && rowNo === selfRow) continue;
    var r = s.rows[i];
    var have = fcSeUniquenessKey_(function (fld) { var c = s.col(fld); return c === -1 ? '' : r[c]; });
    if (have !== want) continue;
    function cell(n) { var c = s.col(n); return c === -1 ? '' : String(r[c] == null ? '' : r[c]).trim(); }
    return { event_fc_id: iId === -1 ? '' : String(r[iId] == null ? '' : r[iId]).trim(),
      event_start_date: cell('event_start_date'), event_end_date: cell('event_end_date'),
      campaign_id: cell('campaign_id'), key: want };
  }
  return null;
}

/**
 * Locate the sheet row (1-based) for a special event by its STABLE BUSINESS KEY, so a re-save /
 * double-click / retry updates the SAME row instead of creating a duplicate — even when the row's
 * event_fc_id is still blank (legacy rows). Primary key = campaign_id + campaign_sku_line_id (the
 * campaign line is 1:1 with its event FC). Fallback = campaign_id + marketplace_id + sku + event_month
 * + year. Returns -1 when no match. NEVER keys on event_name / sku-alone / row number.
 */
function fcSpecialEventFindRowByKey_(s, body) {
  var iCmp = s.col('campaign_id'), iLine = s.col('campaign_sku_line_id'), iMkId = s.col('marketplace_id'),
      iSku = s.col('sku'), iMonth = s.col('event_month'), iYear = s.col('year');
  if (iCmp === -1) return -1;
  var cmp = fcEvtUp_(body.campaign_id);
  if (!cmp) return -1;   // an event FC must link to a campaign (validated by caller)
  var line = fcEvtUp_(body.campaign_sku_line_id);
  var mkid = fcEvtUp_(body.marketplace_id), sku = fcEvtUp_(body.sku),
      month = fcEvtUp_(body.event_month), year = fcEvtUp_(body.year);
  for (var i = 1; i < s.rows.length; i++) {
    var r = s.rows[i];
    if (fcEvtUp_(r[iCmp]) !== cmp) continue;
    if (line) {                       // primary key: campaign_id + campaign_sku_line_id
      if (iLine !== -1 && fcEvtUp_(r[iLine]) === line) return i + 1;
      continue;
    }
    // fallback key: campaign_id + marketplace_id + sku + event_month + year
    if (iSku !== -1 && fcEvtUp_(r[iSku]) !== sku) continue;
    if (mkid && iMkId !== -1 && fcEvtUp_(r[iMkId]) !== mkid) continue;
    if (month && iMonth !== -1 && fcEvtUp_(r[iMonth]) !== month) continue;
    if (year && iYear !== -1 && fcEvtUp_(r[iYear]) !== year) continue;
    return i + 1;
  }
  return -1;
}

// ==============================================================================================
// FC-SUMMARY-R2B-A3-R1 §5 — THE SPECIAL EVENT VERSION TOKEN.
//
// fc_target_rules has carried an optimistic-concurrency token since R2B-A2-R5-F5 and fc_special_events
// has not, so two operators editing the same event's fc_qty resolved last-write-wins and the loser's
// number vanished with a success message. The mechanism is not re-invented here: it is the SAME
// content fingerprint, for the same reasons set out at FC_TR_FINGERPRINT_FIELDS_ — no clock, no
// timezone, no precision assumption, and computed identically from a sheet row and from a workspace
// JSON row.
//
// WHAT IS IN IT, AND WHAT IS DELIBERATELY NOT.
//
//   · event_fc_id is excluded: it identifies the row, it does not describe it.
//   · the audit columns are excluded: they are set BY the write, so a token carrying them would be
//     stale the moment it was issued.
//   · event_start_date and event_end_date are excluded, and this is the one exclusion that is not
//     obvious. They are a snapshot of the campaign's window, which is the CAMPAIGN's identity (see
//     20_ CAMPAIGN_KEY_FIELDS_): an operator cannot edit them here, because changing the window names
//     a different campaign. They are also the two columns that cannot survive the round trip — a
//     sheet Date read server-side as the local calendar day 2027-11-24 reaches the client as the ISO
//     instant 2027-11-23T16:00:00Z, and a version check that fails for a timezone reason is worse
//     than no version check at all, because it teaches operators to click past it.
// ==============================================================================================
var FC_SE_FINGERPRINT_FIELDS_ = ['campaign_id', 'campaign_sku_line_id', 'company', 'country',
  'marketplace', 'marketplace_id', 'scope_type', 'scope_id', 'sku', 'series', 'category',
  'event_name', 'event_period', 'event_month', 'year', 'fc_qty', 'note'];
var FC_SE_FINGERPRINT_NUMERIC_ = ['event_month', 'year', 'fc_qty'];

/** Numeric normalisation: '' stays '', 3000 and '3000' and '3000.0' all become '3000'. */
function fcSeNum_(v) {
  var t = String(v == null ? '' : v).trim();
  if (t === '') return '';
  var n = Number(t);
  return isFinite(n) ? String(n) : t;
}

/** The row's content fingerprint. Identical for a sheet row and a workspace JSON row. */
function fcSeFingerprint_(o) {
  o = o || {};
  var parts = [];
  for (var i = 0; i < FC_SE_FINGERPRINT_FIELDS_.length; i++) {
    var f = FC_SE_FINGERPRINT_FIELDS_[i];
    parts.push(FC_SE_FINGERPRINT_NUMERIC_.indexOf(f) !== -1 ? fcSeNum_(o[f]) : String(o[f] == null ? '' : o[f]).trim());
  }
  return parts.join('|');
}

/** One existing row as { rowNumber, id, fingerprint, updated_at, row }. */
function fcSeRowAt_(s, rowNumber) {
  var r = s.rows[rowNumber - 1];
  if (!r) return null;
  var obj = {};
  for (var h = 0; h < s.headers.length; h++) { if (s.headers[h]) obj[s.headers[h]] = r[h]; }
  var iId = s.col('event_fc_id');
  return {
    rowNumber: rowNumber,
    id: String(iId === -1 ? '' : (r[iId] == null ? '' : r[iId])).trim(),
    fingerprint: fcSeFingerprint_(obj),
    updated_at: String(obj.updated_at == null ? '' : obj.updated_at).trim(),
    row: obj
  };
}

/** The complete canonical row, read back FROM THE SHEET after the write — never composed from the
    request, so the receipt cannot claim a value the sheet does not hold. */
function fcSeReceiptFor_(sheet, eventFcId) {
  var s2 = fcWriteReadSheet_(sheet);
  var iId = s2.col('event_fc_id');
  if (iId === -1) return null;
  for (var i = 1; i < s2.rows.length; i++) {
    if (fcEvtUp_(s2.rows[i][iId]) !== fcEvtUp_(eventFcId)) continue;
    var hit = fcSeRowAt_(s2, i + 1);
    var out = {};
    FC_SPECIAL_EVENTS_HEADERS_.forEach(function (h) {
      var v = hit.row[h];
      out[h] = (v === undefined || v === null) ? '' : (v instanceof Date ? v.toISOString() : v);
    });
    out.row_version = hit.fingerprint;
    return out;
  }
  return null;
}

/**
 * Upsert one fc_special_events row keyed on the canonical `event_fc_id` PK. Resolution order:
 *   1. explicit body.event_fc_id → that row;
 *   2. else business-key match (fcSpecialEventFindRowByKey_) → that row (idempotent retry);
 *   3. else CREATE a new row.
 * On CREATE, and on UPDATE of a row whose event_fc_id is blank (legacy), a NEW backend id
 * `EFC-<12-hex>` is generated and written (inline per-row — this is the row being saved, not a batch
 * backfill). On UPDATE, an existing non-blank event_fc_id is PRESERVED (never regenerated).
 *
 * R2B-A3-R1 — an UPDATE additionally requires body.expected_row_version, the fingerprint observed when
 * the row was read. A save composed as a NEW event carries none and therefore cannot land on a row the
 * operator has never seen; a save whose values already equal the stored ones writes NOTHING.
 *
 * Returns { event_fc_id, created, unchanged, row_version, row } on success, or { refusal: {error,
 * detail, ...} } — a typed, zero-write refusal the callers turn into success:false.
 */
function fcSpecialEventUpsert_(ss, body, actor) {
  var headers = FC_SPECIAL_EVENTS_HEADERS_;
  var sheet = fcWriteEnsureSheet_(ss, 'fc_special_events', headers, FC_SCHEMA_BY_NAME_);
  fcWriteEnsureColumns_(sheet, headers);
  var s = fcWriteReadSheet_(sheet);
  var now = fcWriteTimestamp_();
  var iId = s.col('event_fc_id');
  if (iId === -1) throw new Error('event_fc_id column not found in fc_special_events');

  var explicitId = String(body.event_fc_id || '').trim();
  var targetRow = -1;
  if (explicitId) {
    for (var i = 1; i < s.rows.length; i++) { if (fcEvtUp_(s.rows[i][iId]) === fcEvtUp_(explicitId)) { targetRow = i + 1; break; } }
  }
  if (explicitId && targetRow === -1) {
    // An id that names no row is not a create request. Minting a second row under the id the caller
    // believed it was updating is how one event becomes two.
    return { refusal: { error: 'SPECIAL_EVENT_NOT_FOUND',
      detail: 'No special event carries event_fc_id ' + explicitId + '. Nothing was written.' } };
  }
  if (targetRow === -1) targetRow = fcSpecialEventFindRowByKey_(s, body);

  function genId() { return 'EFC-' + Utilities.getUuid().substring(0, 12).toUpperCase(); }
  function setCell(row, name, value) { var c = s.col(name); if (c !== -1) sheet.getRange(row, c + 1).setValue(value); }

  // §3 — THE UNIQUENESS GATE. Before the create branch, and before any cell is written. An UPDATE is
  // checked too and excludes its own row, so a save that RENAMES an event onto another one's key is
  // refused rather than producing the duplicate by the back door.
  var seConflict = fcSeUniquenessConflict_(s, body, targetRow);
  if (seConflict) {
    return { refusal: { error: 'DUPLICATE_SPECIAL_EVENT_IDENTITY',
      detail: 'A special event already exists for ' + fcEvtUp_(body.sku) + ' / '
        + fcEvtUp_(body.event_name) + ' / ' + fcEvtUp_(body.year) + ' in this marketplace (event_fc_id '
        + (seConflict.event_fc_id || '(blank)') + ', window ' + (seConflict.event_start_date || '?')
        + ' to ' + (seConflict.event_end_date || '?')
        + '). One event flag in one target year is one event, whatever its dates — edit the existing event instead of creating a second. Nothing was written.',
      event_fc_id: seConflict.event_fc_id,
      conflict: seConflict } };
  }

  if (targetRow === -1) {
    // CREATE
    var id = explicitId || genId();
    var createObj = {}; createObj.event_fc_id = id;
    headers.forEach(function (h) { if (body.hasOwnProperty(h) && h !== 'event_fc_id') createObj[h] = body[h]; });
    createObj.created_by = actor; createObj.created_at = now; createObj.updated_by = actor; createObj.updated_at = now;
    fcWriteAppendByHeader_(sheet, createObj);
    return { event_fc_id: id, created: true, unchanged: false,
      row_version: fcSeFingerprint_(createObj), row: fcSeReceiptFor_(sheet, id) };
  }

  // ---- THE VERSION GATE. After the row is located, before anything is written. -------------------
  var prior = fcSeRowAt_(s, targetRow);
  var expectedVersion = String(body.expected_row_version == null ? '' : body.expected_row_version).trim();
  if (!expectedVersion) {
    // A NEW-EVENT SAVE MAY NOT SILENTLY BECOME AN UPDATE — the same rule, and the same sentence, that
    // handleUpsertFcTargetRule_ already applies to a rule. The builder composes a versionless save
    // only when
    // its read model held no match, so arriving here means the model was stale.
    return { refusal: { error: 'STALE_SPECIAL_EVENT_VERSION',
      detail: 'A special event already exists for this campaign line (event_fc_id ' + (prior.id || '(blank)')
        + '). This save carries no expected version and cannot be applied over one. Load the latest data and re-enter the change. Nothing was written.',
      event_fc_id: prior.id,
      current_row_version: prior.fingerprint } };
  }
  if (expectedVersion !== prior.fingerprint) {
    return { refusal: { error: 'STALE_SPECIAL_EVENT_VERSION',
      detail: 'This special event changed after it was loaded. Load the latest data and re-enter the change. Nothing was written.',
      event_fc_id: prior.id,
      current_row_version: prior.fingerprint,
      expected_row_version: expectedVersion,
      current_updated_at: prior.updated_at,
      current: fcSeReceiptFor_(sheet, prior.id) } };
  }

  // ---- UNCHANGED. A save that would write the values already stored writes nothing — not even
  // updated_at. Opening an event and pressing Save must not rewrite its history. -------------------
  var incoming = {};
  FC_SE_FINGERPRINT_FIELDS_.forEach(function (f) {
    incoming[f] = Object.prototype.hasOwnProperty.call(body, f) ? body[f] : prior.row[f];
  });
  if (prior.id && fcSeFingerprint_(incoming) === prior.fingerprint) {
    return { event_fc_id: prior.id, created: false, unchanged: true,
      row_version: prior.fingerprint, row: fcSeReceiptFor_(sheet, prior.id) };
  }

  // UPDATE — preserve existing id; backfill inline only if blank.
  var existing = String(s.rows[targetRow - 1][iId] || '').trim();
  var finalId = existing || explicitId || genId();
  setCell(targetRow, 'event_fc_id', finalId);
  headers.forEach(function (h) {
    if (h === 'event_fc_id' || h === 'created_by' || h === 'created_at') return;
    if (body.hasOwnProperty(h)) setCell(targetRow, h, body[h]);
  });
  setCell(targetRow, 'updated_by', actor);
  setCell(targetRow, 'updated_at', now);
  var after = fcSeReceiptFor_(sheet, finalId);
  return { event_fc_id: finalId, created: false, unchanged: false,
    row_version: after ? after.row_version : '', row: after };
}

/**
 * Create/update a special event. Body: { event_fc_id?, campaign_id, campaign_sku_line_id?,
 * company, country, marketplace, marketplace_id?, scope_type?, scope_id?, sku, series?, category?,
 * event_name, event_period?, event_start_date?, event_end_date?, event_month?, year?, fc_qty, note?, actor? }
 * The backend generates/owns `event_fc_id` (canonical PK) — the frontend never supplies it. Idempotent
 * by campaign_id + campaign_sku_line_id (stable business key). Validates: campaign_id, sku/scope_id,
 * event_name, fc_qty.
 */
function handleUpsertFcSpecialEvent_(body) {
  body = body || {};
  var actor = String(body.updated_by || body.actor || 'fc-summary').trim();
  // ---- Validation (before any write) ----
  if (!String(body.campaign_id || '').trim()) {
    return jsonResponse_({ success: false, error: 'Missing campaign_id — an event forecast must link to a campaign (write campaigns → campaign_sku_lines first)' });
  }
  if (!String(body.sku || '').trim() && !String(body.scope_id || '').trim()) {
    return jsonResponse_({ success: false, error: 'Missing sku / scope_id for special event' });
  }
  if (!String(body.event_name || '').trim()) {
    return jsonResponse_({ success: false, error: 'Missing event_name' });
  }
  var fcq = Number(body.fc_qty);
  if (body.fc_qty === '' || body.fc_qty == null || isNaN(fcq) || fcq < 0) {
    return jsonResponse_({ success: false, error: 'Invalid fc_qty (must be a number ≥ 0)' });
  }
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var result;
  try {
    result = fcSpecialEventUpsert_(ss, body, actor);
  } catch (e) {
    return jsonResponse_({ success: false, error: String(e && e.message ? e.message : e) });
  }
  // A typed refusal is a PROVEN ZERO-WRITE, and it is reported as one: success:false carrying the
  // token, so the page can tell it from a transport failure whose outcome is genuinely unknown.
  if (result && result.refusal) {
    var ref = result.refusal;
    return jsonResponse_({ success: false, error: ref.error, detail: ref.detail,
      event_fc_id: ref.event_fc_id, current_row_version: ref.current_row_version,
      expected_row_version: ref.expected_row_version, current_updated_at: ref.current_updated_at,
      current: ref.current, wrote: 0 });
  }
  return jsonResponse_({ success: true, data: result });
}

/**
 * Batch upsert of special-event forecasts (Special-Event inline edit — FC hotfix). Body: { rows:[{event_fc_id,
 * campaign_id, event_name, sku|scope_id, fc_qty, ...}], options? }. Reuses the SAME canonical row upsert
 * (fcSpecialEventUpsert_) as the single-event path — NO competing implementation. Each row is validated exactly
 * like handleUpsertFcSpecialEvent_ (campaign_id + event_name + sku/scope_id + numeric fc_qty ≥ 0); invalid rows are
 * SKIPPED with a reason (never a partial silent success). No Sheet/Header mutation beyond the shared writer.
 */
function handleImportFcSpecialEventsBatch_(body) {
  body = body || {};
  var rows = Array.isArray(body.rows) ? body.rows : [];
  var actor = String(body.updated_by || body.actor || 'fc-summary').trim();
  if (!rows.length) return jsonResponse_({ success: false, error: 'No rows to save' });
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var results = [], created = 0, updated = 0, skipped = 0, unchanged = 0;
  for (var i = 0; i < rows.length; i++) {
    var r = rows[i] || {};
    var reason = '';
    if (!String(r.campaign_id || '').trim()) reason = 'missing_campaign_id';
    else if (!String(r.sku || '').trim() && !String(r.scope_id || '').trim()) reason = 'missing_sku_or_scope_id';
    else if (!String(r.event_name || '').trim()) reason = 'missing_event_name';
    else { var q = Number(r.fc_qty); if (r.fc_qty === '' || r.fc_qty == null || isNaN(q) || q < 0) reason = 'invalid_fc_qty'; }
    if (reason) { skipped++; results.push({ index: i, event_fc_id: r.event_fc_id || '', skipped: true, reason: reason }); continue; }
    try {
      var res = fcSpecialEventUpsert_(ss, r, actor);   // canonical row upsert (event_fc_id exact, else business key)
      // R2B-A3-R1 — a stale or unlocatable row is REFUSED PER ROW, with its token, and the rest of the
      // batch still runs. It is counted as skipped because that is what it is: zero cells written.
      if (res && res.refusal) {
        skipped++;
        results.push({ index: i, event_fc_id: res.refusal.event_fc_id || r.event_fc_id || '', skipped: true,
          reason: res.refusal.error, detail: res.refusal.detail,
          current_row_version: res.refusal.current_row_version });
        continue;
      }
      if (res && res.created) created++;
      else if (res && res.unchanged) unchanged++;
      else updated++;
      results.push({ index: i, event_fc_id: res && res.event_fc_id, created: !!(res && res.created),
        unchanged: !!(res && res.unchanged), row_version: (res && res.row_version) || '' });
    } catch (e) {
      skipped++; results.push({ index: i, event_fc_id: r.event_fc_id || '', skipped: true, reason: String(e && e.message ? e.message : e) });
    }
  }
  return jsonResponse_({ success: true, data: { summary: { created: created, updated: updated,
    unchanged: unchanged, skipped: skipped, total: rows.length }, results: results } });
}

/** Delete a special event by event_fc_id (accepts legacy event_id). Body: { event_fc_id? | event_id? }. */
function handleDeleteFcSpecialEvent_(body) {
  var id = String((body && (body.event_fc_id || body.event_id)) || '').trim();
  if (!id) return jsonResponse_({ success: false, error: 'Missing event_fc_id' });
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  // FC-SUMMARY-R2B-A2 — the delete is now schema-gated like every other write on this table.
  var res = fcWriteDelete_(ss, 'fc_special_events', 'event_fc_id', id, FC_SPECIAL_EVENTS_HEADERS_, FC_SCHEMA_BY_NAME_);
  if (!res.deleted && res.reason === 'not_found') {   // legacy fallback: a row whose PK column is the old event_id
    res = fcWriteDelete_(ss, 'fc_special_events', 'event_id', id, FC_SPECIAL_EVENTS_HEADERS_, FC_SCHEMA_BY_NAME_);
  }
  return jsonResponse_({ success: true, data: res });
}

/**
 * READ-ONLY audit of blank `event_fc_id` rows (no write). Body: {}. Returns counts + how many blank
 * rows are safely re-identifiable by the business key (campaign_id + campaign_sku_line_id), potential
 * duplicate business keys, and which linking fields are populated. Use this BEFORE any backfill.
 */
function handleAuditFcSpecialEventIds_(body) {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName('fc_special_events');
  if (!sheet) return jsonResponse_({ success: true, data: { sheet_missing: true } });
  var s = fcWriteReadSheet_(sheet);
  var iId = s.col('event_fc_id'), iCmp = s.col('campaign_id'), iLine = s.col('campaign_sku_line_id'),
      iSku = s.col('sku'), iMkId = s.col('marketplace_id'), iMonth = s.col('event_month'), iYear = s.col('year');
  var total = 0, blank = 0, blankWithLineKey = 0, blankWithFallbackKey = 0, hasLegacyEventIdCol = (s.col('event_id') !== -1);
  var keySeen = {}, dupKeys = 0;
  for (var i = 1; i < s.rows.length; i++) {
    var r = s.rows[i];
    if (r.join('') === '') continue;   // skip fully-empty row
    total++;
    var idBlank = iId === -1 || String(r[iId] || '').trim() === '';
    if (!idBlank) continue;
    blank++;
    var hasLine = iLine !== -1 && String(r[iLine] || '').trim() !== '';
    var hasCmp = iCmp !== -1 && String(r[iCmp] || '').trim() !== '';
    if (hasCmp && hasLine) blankWithLineKey++;
    else if (hasCmp && iSku !== -1 && String(r[iSku] || '').trim() !== '') blankWithFallbackKey++;
    var key = fcEvtUp_(iCmp !== -1 ? r[iCmp] : '') + '|' + fcEvtUp_(hasLine ? r[iLine] : '') + '|' +
      fcEvtUp_(iMkId !== -1 ? r[iMkId] : '') + '|' + fcEvtUp_(iSku !== -1 ? r[iSku] : '') + '|' +
      fcEvtUp_(iMonth !== -1 ? r[iMonth] : '') + '|' + fcEvtUp_(iYear !== -1 ? r[iYear] : '');
    if (keySeen[key]) dupKeys++; else keySeen[key] = 1;
  }
  return jsonResponse_({ success: true, data: {
    total_rows: total, blank_event_fc_id: blank,
    blank_reidentifiable_by_campaign_line: blankWithLineKey,
    blank_reidentifiable_by_fallback_key: blankWithFallbackKey,
    blank_with_duplicate_business_key: dupKeys,
    has_legacy_event_id_column: hasLegacyEventIdCol,
    note: 'READ-ONLY audit — no data written. Backfill is a separate manual action (backfillFcSpecialEventIds).'
  } });
}

/**
 * ONE-TIME manual backfill of blank `event_fc_id` — standalone, re-runnable, DRY-RUN FIRST. NOT wired
 * to any auto path. Body:
 *   { }                → DRY-RUN (default): reports would_fill / skipped_no_campaign (ambiguous) /
 *                        duplicate_business_key (collision) / sample — writes NOTHING.
 *   { confirm: true }  → EXECUTE: assigns a fresh EFC-id to each blank-id row that has a campaign_id;
 *                        rows without a campaign_id are skipped (ambiguous / not safely identifiable).
 * Idempotent / re-runnable: a row that already has an id is always skipped. Collision = multiple blank
 * rows sharing the same business key (each still gets its own distinct new id, but is reported).
 */
function handleBackfillFcSpecialEventIds_(body) {
  var dryRun = !(body && body.confirm === true);
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName('fc_special_events');
  if (!sheet) return jsonResponse_({ success: false, error: 'fc_special_events sheet not found' });
  fcWriteEnsureColumns_(sheet, FC_SPECIAL_EVENTS_HEADERS_);
  var s = fcWriteReadSheet_(sheet);
  var iId = s.col('event_fc_id'), iCmp = s.col('campaign_id'), iLine = s.col('campaign_sku_line_id'),
      iMkId = s.col('marketplace_id'), iSku = s.col('sku'), iMonth = s.col('event_month'), iYear = s.col('year');
  if (iId === -1) return jsonResponse_({ success: false, error: 'event_fc_id column missing' });

  // Pass 1 — plan: identify fillable rows, ambiguous rows, and colliding business keys.
  var fillable = [], skippedNoCampaign = 0, keyCount = {}, sample = [];
  for (var i = 1; i < s.rows.length; i++) {
    var r = s.rows[i];
    if (r.join('') === '') continue;
    if (String(r[iId] || '').trim() !== '') continue;                       // already has id → skip (re-runnable)
    if (iCmp === -1 || String(r[iCmp] || '').trim() === '') { skippedNoCampaign++; continue; }   // ambiguous
    var key = fcEvtUp_(r[iCmp]) + '|' + fcEvtUp_(iLine !== -1 ? r[iLine] : '') + '|' +
      fcEvtUp_(iMkId !== -1 ? r[iMkId] : '') + '|' + fcEvtUp_(iSku !== -1 ? r[iSku] : '') + '|' +
      fcEvtUp_(iMonth !== -1 ? r[iMonth] : '') + '|' + fcEvtUp_(iYear !== -1 ? r[iYear] : '');
    keyCount[key] = (keyCount[key] || 0) + 1;
    fillable.push({ row: i + 1, key: key });
    if (sample.length < 10) sample.push({ row: i + 1, sku: iSku !== -1 ? r[iSku] : '', campaign_id: r[iCmp] });
  }
  var collisions = fillable.filter(function (f) { return keyCount[f.key] > 1; }).length;

  if (dryRun) {
    return jsonResponse_({ success: true, data: {
      mode: 'dry_run', would_fill: fillable.length, skipped_no_campaign_id: skippedNoCampaign,
      collision_duplicate_business_key: collisions, sample: sample,
      note: 'DRY-RUN — nothing written. Re-run with { confirm: true } to execute. Ambiguous rows (no campaign_id) are never auto-filled; colliding rows each get a distinct new EFC- id.'
    } });
  }

  // Pass 2 — execute (each fillable row gets a distinct new id).
  var filled = 0;
  for (var k = 0; k < fillable.length; k++) {
    sheet.getRange(fillable[k].row, iId + 1).setValue('EFC-' + Utilities.getUuid().substring(0, 12).toUpperCase());
    filled++;
  }
  return jsonResponse_({ success: true, data: {
    mode: 'executed', backfilled: filled, skipped_no_campaign_id: skippedNoCampaign,
    collision_duplicate_business_key: collisions
  } });
}

// ---- fc_target_rules ----

// R2B-A2-R5-F2 §4 — THE TARGET RULE WRITE HAS ITS OWN IDENTITY NOW.
//
// It used to go through the shared fcWriteUpsert_, whose business key is `target_rule_id` ALONE. Three
// consequences, all of them live:
//   - the FC Summary modal never sends an id, so a second save of the SAME rule APPENDED a duplicate. The
//     frontend single-flight guard stops a double-click; it does not stop a re-save, a reload, or a second
//     operator. And a duplicate business identity is now a hard refusal in every resolver, so two rows do
//     not merely disagree — they disable the rule.
//   - with an id, every field was overwritten unguarded, so an id belonging to ResTW/US/Amazon could be
//     repointed at KM-EU/DE/Amazon and the rule would silently change which site it governed.
//   - no LockService anywhere, so two concurrent creates both read "no match" and both appended.
//
// The shared fcWriteUpsert_ is deliberately NOT changed — campaigns and special events keep their contract.
var FC_TR_SCOPE_TYPES_ = ['CATEGORY', 'SERIES', 'SKU'];
var FC_TR_RETIRED_IDENTITY_ = 'ALL';
var FC_TR_KEY_FIELDS_ = ['year', 'company', 'country', 'marketplace'];
var FC_TR_LOCK_MS_ = 30000;

function fcTrStr_(v) { return String(v === undefined || v === null ? '' : v).trim(); }
function fcTrUp_(v) { return fcTrStr_(v).toUpperCase(); }
/** ONE mapping for however a scope is spelled; '' when it is not a supported scope. */
function fcTrScopeType_(v) {
  var u = fcTrUp_(v);
  return FC_TR_SCOPE_TYPES_.indexOf(u) !== -1 ? u : '';
}
/** A usable identity value: non-blank and not the retired `All` sentinel. */
function fcTrIdentityUsable_(v) {
  var t = fcTrStr_(v);
  return !!t && fcTrUp_(t) !== FC_TR_RETIRED_IDENTITY_;
}
/** year|company|country|marketplace|scope_type|scope_id — the canonical business key, uppercased. */
function fcTrBusinessKey_(o) {
  return [fcTrUp_(o.year), fcTrUp_(o.company), fcTrUp_(o.country), fcTrUp_(o.marketplace),
    fcTrUp_(o.scope_type), fcTrUp_(o.scope_id)].join('|');
}
/** The dimension a scope_id must name, taken from the row's own columns. */
function fcTrScopeDimension_(row, scopeType) {
  if (scopeType === 'SKU') return fcTrStr_(row.sku);
  if (scopeType === 'SERIES') return fcTrStr_(row.series);
  return fcTrStr_(row.category);
}

/**
 * Validate a Target Rule body against the frozen contract. Returns { ok, error, detail, norm }.
 * Nothing is written by a body that fails here.
 */
function fcTrValidateBody_(body) {
  var b = body || {};
  var missing = [];
  for (var i = 0; i < FC_TR_KEY_FIELDS_.length; i++) {
    if (!fcTrIdentityUsable_(b[FC_TR_KEY_FIELDS_[i]])) missing.push(FC_TR_KEY_FIELDS_[i]);
  }
  if (missing.length) {
    return { ok: false, error: 'TARGET_RULE_IDENTITY_INCOMPLETE',
      detail: 'Blank or `All` is not an identity: ' + missing.join(', ')
        + '. Site identity is exact (FC_SUMMARY_SPEC §4.1).' };
  }
  var st = fcTrScopeType_(b.scope_type);
  if (!st) {
    return { ok: false, error: 'TARGET_RULE_SCOPE_TYPE_INVALID',
      detail: 'scope_type must be one of ' + FC_TR_SCOPE_TYPES_.join(', ') + '; received "' + fcTrStr_(b.scope_type) + '".' };
  }
  if (!fcTrIdentityUsable_(b.scope_id)) {
    return { ok: false, error: 'TARGET_RULE_SCOPE_ID_INVALID', detail: 'scope_id is blank or `All`.' };
  }
  // scope_id must agree with the dimension column it names, so a row cannot claim SKU scope while its
  // sku column says something else.
  var dim = fcTrScopeDimension_(b, st);
  if (dim && fcTrUp_(dim) !== fcTrUp_(b.scope_id)) {
    return { ok: false, error: 'TARGET_RULE_SCOPE_ID_MISMATCH',
      detail: 'scope_type ' + st + ' has scope_id "' + fcTrStr_(b.scope_id) + '" but its own column says "' + dim + '".' };
  }
  var norm = {};
  for (var k in b) { if (Object.prototype.hasOwnProperty.call(b, k)) norm[k] = b[k]; }
  norm.scope_type = st;                                   // persisted uppercase, through the one mapping
  norm.scope_id = fcTrStr_(b.scope_id);
  return { ok: true, norm: norm, scopeType: st, key: fcTrBusinessKey_(norm) };
}

// ==============================================================================================
// R2B-A2-R5-F5 §4 — THE VERSION TOKEN, AND WHY IT IS NOT updated_at.
//
// The obvious optimistic-concurrency token is the timestamp the modal saw when it hydrated. It is
// not good enough here, and the round that asked for this said plainly not to pretend otherwise:
//
//   · fcWriteTimestamp_() formats 'yyyy-MM-dd HH:mm:ss' — SECOND precision, no milliseconds. Two
//     saves inside one second are indistinguishable, and the script lock makes same-second writes
//     MORE likely rather than less: the loser resumes the instant the winner releases.
//   · it is written in the SCRIPT timezone while the client reads an ISO-8601 UTC string back out
//     of the workspace payload, so the two sides must agree on a timezone conversion before they
//     can agree on equality. A version check that can fail for a daylight-saving reason is worse
//     than no version check, because it teaches operators to click past it.
//
// So the token is a FINGERPRINT OF THE ROW'S OWN DATA. It compares what the values ARE, which is
// the question actually being asked: has anybody changed this rule since I read it? It needs no
// clock, no timezone and no precision assumption, and it is computed identically from a sheet row
// and from a workspace JSON row because it normalises both through the same two functions.
//
// A consequence worth stating: if another operator wrote the IDENTICAL values, the fingerprint
// matches and the write proceeds. That is correct. The hazard being guarded is losing somebody's
// change, and a change that changed nothing cannot be lost.
// ==============================================================================================
var FC_TR_MONTH_KEYS_ = ['jan_pct', 'feb_pct', 'mar_pct', 'apr_pct', 'may_pct', 'jun_pct',
  'jul_pct', 'aug_pct', 'sep_pct', 'oct_pct', 'nov_pct', 'dec_pct'];
// The fields a rule MEANS. target_rule_id is excluded (it identifies the row, it is not its content)
// and so are the audit columns (they are set BY the write, so including them would make every token
// stale the moment it was issued).
var FC_TR_FINGERPRINT_FIELDS_ = ['year', 'company', 'country', 'marketplace', 'scope_type', 'scope_id',
  'category', 'series', 'sku', 'target_percentage'].concat(FC_TR_MONTH_KEYS_).concat(['note']);
var FC_TR_FINGERPRINT_NUMERIC_ = ['year', 'target_percentage'].concat(FC_TR_MONTH_KEYS_);

/** Numeric normalisation: '' stays '', 110 and '110' and '110.0' all become '110'. */
function fcTrNum_(v) {
  var t = fcTrStr_(v);
  if (t === '') return '';
  var n = Number(t);
  return isFinite(n) ? String(n) : t;
}
/** The row's content fingerprint. Identical for a sheet row and a workspace JSON row. */
function fcTrFingerprint_(o) {
  o = o || {};
  var parts = [];
  for (var i = 0; i < FC_TR_FINGERPRINT_FIELDS_.length; i++) {
    var f = FC_TR_FINGERPRINT_FIELDS_[i];
    parts.push(FC_TR_FINGERPRINT_NUMERIC_.indexOf(f) !== -1 ? fcTrNum_(o[f]) : fcTrStr_(o[f]));
  }
  return parts.join('|');
}

/** Every existing row as { rowNumber, id, key, fingerprint, updated_at } — one read, both paths. */
function fcTrIndexRows_(s) {
  var iId = s.col('target_rule_id');
  var out = [];
  for (var i = 1; i < s.rows.length; i++) {
    var r = s.rows[i];
    if (String(r.join('')).trim() === '') continue;
    function cell(name) { var c = s.col(name); return c === -1 ? '' : r[c]; }
    var obj = {};
    for (var h = 0; h < s.headers.length; h++) { if (s.headers[h]) obj[s.headers[h]] = r[h]; }
    out.push({
      rowNumber: i + 1,
      id: fcTrStr_(iId === -1 ? '' : r[iId]),
      key: fcTrBusinessKey_({ year: cell('year'), company: cell('company'), country: cell('country'),
        marketplace: cell('marketplace'), scope_type: cell('scope_type'), scope_id: cell('scope_id') }),
      fingerprint: fcTrFingerprint_(obj),
      updated_at: fcTrStr_(cell('updated_at')),
      row: obj
    });
  }
  return out;
}

/** The complete canonical row, read back FROM THE SHEET after the write — never composed from the
    request, so the receipt cannot claim a value the sheet does not hold. */
function fcTrReceiptFor_(sheet, ruleId) {
  var s2 = fcWriteReadSheet_(sheet);
  var hit = fcTrIndexRows_(s2).filter(function (r) { return r.id === ruleId; });
  if (hit.length !== 1) return null;
  var out = {};
  FC_TARGET_RULES_HEADERS_.forEach(function (h) {
    var v = hit[0].row[h];
    out[h] = (v === undefined || v === null) ? '' : (v instanceof Date ? v.toISOString() : v);
  });
  out.row_version = hit[0].fingerprint;
  out.business_key = hit[0].key;
  return out;
}

/**
 * Create/update a target % rule. Body: { target_rule_id?, company, country, marketplace, scope_type,
 * scope_id, year, category?, series?, sku?, target_percentage?, jan_pct..dec_pct, note?, actor? }
 *
 * Identity is the canonical business key, not the id: the same key always updates the same row, a different
 * key always creates a different rule, and an id whose stored key differs from the payload's refuses.
 */
function handleUpsertFcTargetRule_(body) {
  body = body || {};
  var actor = String(body.updated_by || body.actor || 'fc-summary').trim();

  var v = fcTrValidateBody_(body);
  if (!v.ok) return jsonResponse_({ success: false, error: v.error, detail: v.detail });

  var lock = LockService.getScriptLock();
  try {
    // Two concurrent creates must not both read "no match" and both append.
    if (!lock.tryLock(FC_TR_LOCK_MS_)) {
      return jsonResponse_({ success: false, error: 'TARGET_RULE_LOCK_TIMEOUT',
        detail: 'Another Target Rule write is in progress. Nothing was written.' });
    }
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var sheet = fcWriteEnsureSheet_(ss, 'fc_target_rules', FC_TARGET_RULES_HEADERS_, FC_SCHEMA_BY_NAME_);
    fcWriteEnsureColumns_(sheet, FC_TARGET_RULES_HEADERS_);
    var s = fcWriteReadSheet_(sheet);
    if (s.col('target_rule_id') === -1) {
      return jsonResponse_({ success: false, error: 'target_rule_id column not found in fc_target_rules' });
    }
    var index = fcTrIndexRows_(s);
    var now = fcWriteTimestamp_();
    var suppliedId = fcTrStr_(body.target_rule_id);
    var byKey = index.filter(function (r) { return r.key === v.key; });

    var targetRow = -1, ruleId = '', created = false, matched = null;

    if (suppliedId) {
      // ---- UPDATE BY ID — the id may only ever address a row with the SAME canonical identity ----------
      var byId = index.filter(function (r) { return r.id === suppliedId; });
      if (byId.length === 0) {
        return jsonResponse_({ success: false, error: 'TARGET_RULE_NOT_FOUND',
          detail: 'No rule carries target_rule_id ' + suppliedId + '. Nothing was written.' });
      }
      if (byId.length > 1) {
        return jsonResponse_({ success: false, error: 'DUPLICATE_TARGET_RULE_IDENTITY',
          detail: byId.length + ' rows share target_rule_id ' + suppliedId
            + ' (rows ' + byId.map(function (r) { return r.rowNumber; }).join(', ') + '). Nothing was written.' });
      }
      if (byId[0].key !== v.key) {
        return jsonResponse_({ success: false, error: 'TARGET_RULE_IDENTITY_MISMATCH',
          detail: 'target_rule_id ' + suppliedId + ' belongs to ' + byId[0].key + ', not ' + v.key
            + '. A rule\'s site or scope is never silently repointed. Nothing was written.' });
      }
      targetRow = byId[0].rowNumber;
      ruleId = suppliedId;
      matched = byId[0];
    } else {
      // ---- BY BUSINESS KEY — the same rule updates itself instead of appending a twin -----------------
      if (byKey.length > 1) {
        return jsonResponse_({ success: false, error: 'DUPLICATE_TARGET_RULE_IDENTITY',
          detail: byKey.length + ' rows already carry the identity ' + v.key
            + ' (rows ' + byKey.map(function (r) { return r.rowNumber; }).join(', ')
            + '). Resolve the duplicate before writing. Nothing was written.' });
      }
      if (byKey.length === 1) {
        // R2B-A2-R5-F5 — A NEW-RULE SAVE MAY NOT SILENTLY BECOME AN UPDATE. The client only offers
        // New mode when its read model holds no match, so arriving here means the model was stale:
        // somebody created this identity in between. Updating it would overwrite values the operator
        // in front of this modal has never seen — which is the exact defect this round exists to fix,
        // and it is defended HERE as well as in the page, because the page can always be a copy behind.
        if (!fcTrStr_(body.expected_row_version)) {
          return jsonResponse_({ success: false, error: 'STALE_TARGET_RULE_VERSION',
            detail: 'A rule for ' + v.key + ' already exists (target_rule_id ' + byKey[0].id
              + '). This save was composed as a NEW rule, so it carries no expected version and'
              + ' cannot be applied over one. Load the latest data and re-enter the change.'
              + ' Nothing was written.' });
        }
        targetRow = byKey[0].rowNumber; ruleId = byKey[0].id; matched = byKey[0];
      }
    }

    // ---- THE VERSION GATE. Checked after the row is located and BEFORE anything is written. --------
    if (matched) {
      var expectedVersion = fcTrStr_(body.expected_row_version);
      if (!expectedVersion) {
        return jsonResponse_({ success: false, error: 'TARGET_RULE_VERSION_REQUIRED',
          detail: 'Updating an existing rule requires expected_row_version, the fingerprint observed'
            + ' when the modal was hydrated. Nothing was written.' });
      }
      if (expectedVersion !== matched.fingerprint) {
        return jsonResponse_({ success: false, error: 'STALE_TARGET_RULE_VERSION',
          detail: 'This rule changed after it was loaded. Load the latest data and re-enter the change.'
            + ' Nothing was written.',
          current_row_version: matched.fingerprint,
          expected_row_version: expectedVersion,
          current_updated_at: matched.updated_at,
          current: fcTrReceiptFor_(sheet, ruleId) });
      }
      // ---- UNCHANGED. A save that would write the values already stored writes nothing. -----------
      // The page suppresses this too, but only the server can be sure: it is the one holding the row.
      var incoming = {};
      FC_TR_FINGERPRINT_FIELDS_.forEach(function (f) {
        incoming[f] = Object.prototype.hasOwnProperty.call(v.norm, f) ? v.norm[f] : matched.row[f];
      });
      if (fcTrFingerprint_(incoming) === matched.fingerprint) {
        return jsonResponse_({ success: true, data: {
          id: ruleId, target_rule_id: ruleId, created: false, unchanged: true,
          business_key: v.key, scope_type: v.scopeType,
          row: fcTrReceiptFor_(sheet, ruleId),
          row_version: matched.fingerprint,
          summary: 'unchanged ' + v.key + ' — nothing was written' } });
      }
    }

    if (targetRow === -1) {
      // CREATE
      ruleId = 'fc_target_rules-' + Utilities.getUuid().substring(0, 12).toUpperCase();
      var createObj = { target_rule_id: ruleId };
      FC_TARGET_RULES_HEADERS_.forEach(function (h) {
        if (h !== 'target_rule_id' && Object.prototype.hasOwnProperty.call(v.norm, h)) createObj[h] = v.norm[h];
      });
      createObj.created_by = actor; createObj.created_at = now;
      createObj.updated_by = actor; createObj.updated_at = now;
      fcWriteAppendByHeader_(sheet, createObj);
      created = true;
    } else {
      // UPDATE — ONE range write for the whole row rather than ~28 single-cell calls, so an interruption
      // cannot leave the row half-written with a new marketplace and an old percentage.
      if (!ruleId) ruleId = 'fc_target_rules-' + Utilities.getUuid().substring(0, 12).toUpperCase();
      var width = s.headers.length;
      var existing = sheet.getRange(targetRow, 1, 1, width).getValues()[0];
      for (var c = 0; c < width; c++) {
        var h = s.headers[c];
        if (!h || h === 'created_by' || h === 'created_at') continue;      // creation audit is preserved
        if (h === 'target_rule_id') { existing[c] = ruleId; continue; }
        if (h === 'updated_by') { existing[c] = actor; continue; }
        if (h === 'updated_at') { existing[c] = now; continue; }
        if (Object.prototype.hasOwnProperty.call(v.norm, h)) existing[c] = v.norm[h];
      }
      sheet.getRange(targetRow, 1, 1, width).setValues([existing]);
    }
    SpreadsheetApp.flush();

    // R2B-A2-R5-F5 §5 — THE RECEIPT CARRIES THE WHOLE SAVED ROW, read back from the sheet rather
    // than echoed from the request. The page renders the table from this directly, so a Target Rule
    // becomes visible at write-acknowledgement speed instead of waiting for the 222 KB workspace read
    // that follows it. A receipt composed from the request could not be trusted for that: it would
    // show what was asked for, not what was stored.
    var receipt = fcTrReceiptFor_(sheet, ruleId);
    return jsonResponse_({ success: true, data: {
      id: ruleId,
      target_rule_id: ruleId,
      created: created,
      unchanged: false,
      business_key: v.key,
      scope_type: v.scopeType,
      row: receipt,
      row_version: receipt ? receipt.row_version : '',
      summary: (created ? 'created' : 'updated') + ' ' + v.key
    } });
  } catch (e) {
    return jsonResponse_({ success: false, error: String(e && e.message ? e.message : e) });
  } finally {
    try { lock.releaseLock(); } catch (e2) {}
  }
}

/** Delete a target rule by target_rule_id. Body: { target_rule_id }. */
function handleDeleteFcTargetRule_(body) {
  var id = String((body && body.target_rule_id) || '').trim();
  if (!id) return jsonResponse_({ success: false, error: 'Missing target_rule_id' });
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  // FC-SUMMARY-R2B-A2 — same gate as the Target Rule write, so a delete can never be the laxer door, and the
  // same envelope, so the two Target Rule writes refuse in the same shape instead of one returning a refusal
  // and the other throwing past its handler into the router's catch.
  try {
    return jsonResponse_({ success: true, data: fcWriteDelete_(ss, 'fc_target_rules', 'target_rule_id', id,
      FC_TARGET_RULES_HEADERS_, FC_SCHEMA_BY_NAME_) });
  } catch (e) {
    return jsonResponse_({ success: false, error: String(e && e.message ? e.message : e) });
  }
}
