// ============================================================
// Kitchen Mama Operation System — Apps Script (modularized source mirror)
// 14_fc_write_handlers.gs — FC Summary write path (Phase 1)
//   Special Events (fc_special_events) + Target % Rules (fc_target_rules)
// NOTE: All .gs files in this folder share ONE global scope in the Apps
//       Script project. Copy them into the project TOGETHER and REDEPLOY. No imports.
//
// Scope (Phase 1): read/write for fc_special_events + fc_target_rules ONLY.
//   Does NOT touch fc_regular_forecast (Edit Base FC / Add SKU / Import are Phase 2 / existing).
//   Tabs are auto-created with the documented header row on first WRITE (missing tab is [] on read).
//   Handlers: handleUpsertFcSpecialEvent_ / handleDeleteFcSpecialEvent_
//             handleUpsertFcTargetRule_   / handleDeleteFcTargetRule_
// ============================================================

// fc_special_events header. event_name / event_month / fc_qty are the task-defined columns;
// event_period + year are additional UI-continuity columns (FC Summary Event table shows/filters them).
// 2026-07-22 (ADDITIVE): campaign_id / campaign_sku_line_id link each event forecast back to its
//   parent campaign + campaign line (Special Event Builder writes campaigns → campaign_sku_lines →
//   fc_special_events); marketplace_id is the canonical marketplace identity (company-safe, since the
//   same marketplace NAME can belong to two companies); event_start_date / event_end_date are the
//   linked event-period snapshot (event_period kept as legacy/display; event_month = allocation month).
//   New columns are appended to an EXISTING sheet's header row by fcWriteEnsureColumns_ — never
//   renaming or dropping a live column (migration-safe, no redeploy assumption baked in).
// PK aligned to the CANONICAL name `event_fc_id` (FC_SUMMARY_SPEC §3.1) — 2026-07-22. The prior header
// used `event_id`, which left the real `event_fc_id` PK column BLANK on sheets whose PK is `event_fc_id`
// (fcWriteEnsureColumns_ appended a stray `event_id` column instead). event_fc_id is generated by the
// backend (see handleUpsertFcSpecialEvent_ / fcSpecialEventUpsert_); a legacy `event_id` column, if any,
// is left untouched (never dropped) but no longer written.
var FC_SPECIAL_EVENTS_HEADERS_ = [
  'event_fc_id', 'campaign_id', 'campaign_sku_line_id',
  'company', 'country', 'marketplace', 'marketplace_id', 'scope_type', 'scope_id',
  'sku', 'series', 'category', 'event_name',
  'event_period', 'event_start_date', 'event_end_date', 'event_month', 'year', 'fc_qty',
  'note', 'created_by', 'created_at', 'updated_by', 'updated_at'
];

// fc_target_rules header. scope_type / scope_id + jan_pct..dec_pct are the task-defined columns;
// year / category / series / sku are additional UI-continuity columns (Target table shows them and
// the effective-rule resolver matches on year + scope value).
var FC_TARGET_RULES_HEADERS_ = [
  'target_rule_id', 'company', 'country', 'marketplace', 'scope_type', 'scope_id',
  'year', 'category', 'series', 'sku', 'target_percentage',
  'jan_pct', 'feb_pct', 'mar_pct', 'apr_pct', 'may_pct', 'jun_pct',
  'jul_pct', 'aug_pct', 'sep_pct', 'oct_pct', 'nov_pct', 'dec_pct',
  'note', 'created_by', 'created_at', 'updated_by', 'updated_at'
];

function fcWriteTimestamp_() {
  return Utilities.formatDate(new Date(), Session.getScriptTimeZone(), 'yyyy-MM-dd HH:mm:ss');
}

/** Get (or create with the documented header row) an FC write tab. */
// Production Safety Round S0.5 (RULE S0-2/S0-5): VALIDATE-ONLY (no auto-create / no Header write). Delegates to the
// shared safety adapter (29_); create is migration-only (prodMigrateCreateSheet_), unreachable from Runtime.
function fcWriteEnsureSheet_(ss, name, headers) {
  return prodRequireSheet_(ss, name, headers);
}

/**
 * Production Safety Round S0.5 (RULE S0-2): VALIDATE-ONLY. Normal Runtime no longer appends missing Header columns
 * on write — any missing REQUIRED column fails closed (MISSING_REQUIRED_HEADER) with ZERO mutation. Additive column
 * migration is migration-only (prodMigrateAppendColumns_ in 29_). Returns 0 (validate passed → nothing appended).
 */
function fcWriteEnsureColumns_(sheet, headers) {
  prodRequireColumns_(sheet, (headers || []).filter(function (h) { return !!h; }));
  return 0;
}

/** Read a sheet as { headers, rows(values), col(name) }. */
function fcWriteReadSheet_(sheet) {
  var data = sheet.getDataRange().getValues();
  var headers = (data[0] || []).map(function (h) { return String(h).trim(); });
  return {
    headers: headers,
    rows: data,
    col: function (n) { return headers.indexOf(n); }
  };
}

/** Append a row using the sheet's existing header row (writes only known columns). */
function fcWriteAppendByHeader_(sheet, obj) {
  var lastCol = sheet.getLastColumn();
  var headers = sheet.getRange(1, 1, 1, lastCol).getValues()[0].map(function (h) { return String(h).trim(); });
  var row = new Array(headers.length).fill('');
  for (var i = 0; i < headers.length; i++) {
    if (obj.hasOwnProperty(headers[i]) && obj[headers[i]] !== undefined && obj[headers[i]] !== null) {
      row[i] = obj[headers[i]];
    }
  }
  sheet.appendRow(row);
}

/**
 * Generic header-based upsert by id column. Updates the matching row's known columns (only keys
 * present in body that are also sheet headers), else appends a new row. Stamps created/updated meta.
 * Returns { id, created }.
 */
function fcWriteUpsert_(ss, sheetName, headers, idCol, idValue, body, actor) {
  var sheet = fcWriteEnsureSheet_(ss, sheetName, headers);
  fcWriteEnsureColumns_(sheet, headers);   // ADDITIVE: back-fill any new columns onto a pre-existing sheet
  var s = fcWriteReadSheet_(sheet);
  var now = fcWriteTimestamp_();
  var idColIdx = s.col(idCol);
  if (idColIdx === -1) throw new Error(idCol + ' column not found in ' + sheetName);

  // Locate existing row by id (when an id was supplied).
  var targetRow = -1;
  if (idValue) {
    for (var i = 1; i < s.rows.length; i++) {
      if (String(s.rows[i][idColIdx]).trim() === String(idValue).trim()) { targetRow = i + 1; break; }
    }
  }

  if (targetRow === -1) {
    // Create new.
    var newId = idValue || (sheetName + '-' + Utilities.getUuid().substring(0, 12).toUpperCase());
    var createObj = {};
    createObj[idCol] = newId;
    headers.forEach(function (h) {
      if (body.hasOwnProperty(h) && h !== idCol) createObj[h] = body[h];
    });
    createObj.created_by = actor;
    createObj.created_at = now;
    createObj.updated_by = actor;
    createObj.updated_at = now;
    fcWriteAppendByHeader_(sheet, createObj);
    return { id: newId, created: true };
  }

  // Update existing: only write columns present in body that are real headers (never the id / created_*).
  function setCell(name, value) { var c = s.col(name); if (c !== -1) sheet.getRange(targetRow, c + 1).setValue(value); }
  headers.forEach(function (h) {
    if (h === idCol || h === 'created_by' || h === 'created_at') return;
    if (body.hasOwnProperty(h)) setCell(h, body[h]);
  });
  setCell('updated_by', actor);
  setCell('updated_at', now);
  return { id: String(idValue).trim(), created: false };
}

/** Generic hard-delete by id column. Returns { id, deleted }. */
function fcWriteDelete_(ss, sheetName, idCol, idValue) {
  var sheet = ss.getSheetByName(sheetName);
  if (!sheet) return { id: idValue, deleted: false, reason: 'sheet_not_found' };
  var s = fcWriteReadSheet_(sheet);
  var idColIdx = s.col(idCol);
  if (idColIdx === -1) return { id: idValue, deleted: false, reason: 'id_column_missing' };
  for (var i = 1; i < s.rows.length; i++) {
    if (String(s.rows[i][idColIdx]).trim() === String(idValue).trim()) {
      sheet.deleteRow(i + 1);
      return { id: idValue, deleted: true };
    }
  }
  return { id: idValue, deleted: false, reason: 'not_found' };
}

// ---- fc_special_events ----

// Uppercase-trim compare helper for fc_special_events business-key matching.
function fcEvtUp_(v) { return String(v == null ? '' : v).trim().toUpperCase(); }

/**
 * Locate the sheet row (1-based) for a special event by its STABLE BUSINESS KEY, so a re-save /
 * double-click / retry updates the SAME row instead of creating a duplicate — even when the row's
 * event_fc_id is still blank (legacy rows). Primary key = campaign_id + campaign_sku_line_id (the
 * campaign line is 1:1 with its event FC). Fallback = campaign_id + marketplace_id + sku + event_month
 * + year. Returns -1 when no match. NEVER keys on event_name / sku-alone / row number.
 */
function fcSpecialEventFindRowByKey_(s, body) {
  var iCmp = s.col('campaign_id'), iLine = s.col('campaign_sku_line_id'), iMkId = s.col('marketplace_id'),
      iSku = s.col('sku'), iMonth = s.col('event_month'), iYear = s.col('year');
  if (iCmp === -1) return -1;
  var cmp = fcEvtUp_(body.campaign_id);
  if (!cmp) return -1;   // an event FC must link to a campaign (validated by caller)
  var line = fcEvtUp_(body.campaign_sku_line_id);
  var mkid = fcEvtUp_(body.marketplace_id), sku = fcEvtUp_(body.sku),
      month = fcEvtUp_(body.event_month), year = fcEvtUp_(body.year);
  for (var i = 1; i < s.rows.length; i++) {
    var r = s.rows[i];
    if (fcEvtUp_(r[iCmp]) !== cmp) continue;
    if (line) {                       // primary key: campaign_id + campaign_sku_line_id
      if (iLine !== -1 && fcEvtUp_(r[iLine]) === line) return i + 1;
      continue;
    }
    // fallback key: campaign_id + marketplace_id + sku + event_month + year
    if (iSku !== -1 && fcEvtUp_(r[iSku]) !== sku) continue;
    if (mkid && iMkId !== -1 && fcEvtUp_(r[iMkId]) !== mkid) continue;
    if (month && iMonth !== -1 && fcEvtUp_(r[iMonth]) !== month) continue;
    if (year && iYear !== -1 && fcEvtUp_(r[iYear]) !== year) continue;
    return i + 1;
  }
  return -1;
}

/**
 * Upsert one fc_special_events row keyed on the canonical `event_fc_id` PK. Resolution order:
 *   1. explicit body.event_fc_id → that row;
 *   2. else business-key match (fcSpecialEventFindRowByKey_) → that row (idempotent retry);
 *   3. else CREATE a new row.
 * On CREATE, and on UPDATE of a row whose event_fc_id is blank (legacy), a NEW backend id
 * `EFC-<12-hex>` is generated and written (inline per-row — this is the row being saved, not a batch
 * backfill). On UPDATE, an existing non-blank event_fc_id is PRESERVED (never regenerated). Returns
 * { event_fc_id, created }.
 */
function fcSpecialEventUpsert_(ss, body, actor) {
  var headers = FC_SPECIAL_EVENTS_HEADERS_;
  var sheet = fcWriteEnsureSheet_(ss, 'fc_special_events', headers);
  fcWriteEnsureColumns_(sheet, headers);
  var s = fcWriteReadSheet_(sheet);
  var now = fcWriteTimestamp_();
  var iId = s.col('event_fc_id');
  if (iId === -1) throw new Error('event_fc_id column not found in fc_special_events');

  var explicitId = String(body.event_fc_id || '').trim();
  var targetRow = -1;
  if (explicitId) {
    for (var i = 1; i < s.rows.length; i++) { if (fcEvtUp_(s.rows[i][iId]) === fcEvtUp_(explicitId)) { targetRow = i + 1; break; } }
  }
  if (targetRow === -1) targetRow = fcSpecialEventFindRowByKey_(s, body);

  function genId() { return 'EFC-' + Utilities.getUuid().substring(0, 12).toUpperCase(); }
  function setCell(row, name, value) { var c = s.col(name); if (c !== -1) sheet.getRange(row, c + 1).setValue(value); }

  if (targetRow === -1) {
    // CREATE
    var id = explicitId || genId();
    var createObj = {}; createObj.event_fc_id = id;
    headers.forEach(function (h) { if (body.hasOwnProperty(h) && h !== 'event_fc_id') createObj[h] = body[h]; });
    createObj.created_by = actor; createObj.created_at = now; createObj.updated_by = actor; createObj.updated_at = now;
    fcWriteAppendByHeader_(sheet, createObj);
    return { event_fc_id: id, created: true };
  }
  // UPDATE — preserve existing id; backfill inline only if blank.
  var existing = String(s.rows[targetRow - 1][iId] || '').trim();
  var finalId = existing || explicitId || genId();
  setCell(targetRow, 'event_fc_id', finalId);
  headers.forEach(function (h) {
    if (h === 'event_fc_id' || h === 'created_by' || h === 'created_at') return;
    if (body.hasOwnProperty(h)) setCell(targetRow, h, body[h]);
  });
  setCell(targetRow, 'updated_by', actor);
  setCell(targetRow, 'updated_at', now);
  return { event_fc_id: finalId, created: false };
}

/**
 * Create/update a special event. Body: { event_fc_id?, campaign_id, campaign_sku_line_id?,
 * company, country, marketplace, marketplace_id?, scope_type?, scope_id?, sku, series?, category?,
 * event_name, event_period?, event_start_date?, event_end_date?, event_month?, year?, fc_qty, note?, actor? }
 * The backend generates/owns `event_fc_id` (canonical PK) — the frontend never supplies it. Idempotent
 * by campaign_id + campaign_sku_line_id (stable business key). Validates: campaign_id, sku/scope_id,
 * event_name, fc_qty.
 */
function handleUpsertFcSpecialEvent_(body) {
  body = body || {};
  var actor = String(body.updated_by || body.actor || 'fc-summary').trim();
  // ---- Validation (before any write) ----
  if (!String(body.campaign_id || '').trim()) {
    return jsonResponse_({ success: false, error: 'Missing campaign_id — an event forecast must link to a campaign (write campaigns → campaign_sku_lines first)' });
  }
  if (!String(body.sku || '').trim() && !String(body.scope_id || '').trim()) {
    return jsonResponse_({ success: false, error: 'Missing sku / scope_id for special event' });
  }
  if (!String(body.event_name || '').trim()) {
    return jsonResponse_({ success: false, error: 'Missing event_name' });
  }
  var fcq = Number(body.fc_qty);
  if (body.fc_qty === '' || body.fc_qty == null || isNaN(fcq) || fcq < 0) {
    return jsonResponse_({ success: false, error: 'Invalid fc_qty (must be a number ≥ 0)' });
  }
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var result;
  try {
    result = fcSpecialEventUpsert_(ss, body, actor);
  } catch (e) {
    return jsonResponse_({ success: false, error: String(e && e.message ? e.message : e) });
  }
  return jsonResponse_({ success: true, data: result });
}

/** Delete a special event by event_fc_id (accepts legacy event_id). Body: { event_fc_id? | event_id? }. */
function handleDeleteFcSpecialEvent_(body) {
  var id = String((body && (body.event_fc_id || body.event_id)) || '').trim();
  if (!id) return jsonResponse_({ success: false, error: 'Missing event_fc_id' });
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var res = fcWriteDelete_(ss, 'fc_special_events', 'event_fc_id', id);
  if (!res.deleted && res.reason === 'not_found') res = fcWriteDelete_(ss, 'fc_special_events', 'event_id', id);   // legacy fallback
  return jsonResponse_({ success: true, data: res });
}

/**
 * READ-ONLY audit of blank `event_fc_id` rows (no write). Body: {}. Returns counts + how many blank
 * rows are safely re-identifiable by the business key (campaign_id + campaign_sku_line_id), potential
 * duplicate business keys, and which linking fields are populated. Use this BEFORE any backfill.
 */
function handleAuditFcSpecialEventIds_(body) {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName('fc_special_events');
  if (!sheet) return jsonResponse_({ success: true, data: { sheet_missing: true } });
  var s = fcWriteReadSheet_(sheet);
  var iId = s.col('event_fc_id'), iCmp = s.col('campaign_id'), iLine = s.col('campaign_sku_line_id'),
      iSku = s.col('sku'), iMkId = s.col('marketplace_id'), iMonth = s.col('event_month'), iYear = s.col('year');
  var total = 0, blank = 0, blankWithLineKey = 0, blankWithFallbackKey = 0, hasLegacyEventIdCol = (s.col('event_id') !== -1);
  var keySeen = {}, dupKeys = 0;
  for (var i = 1; i < s.rows.length; i++) {
    var r = s.rows[i];
    if (r.join('') === '') continue;   // skip fully-empty row
    total++;
    var idBlank = iId === -1 || String(r[iId] || '').trim() === '';
    if (!idBlank) continue;
    blank++;
    var hasLine = iLine !== -1 && String(r[iLine] || '').trim() !== '';
    var hasCmp = iCmp !== -1 && String(r[iCmp] || '').trim() !== '';
    if (hasCmp && hasLine) blankWithLineKey++;
    else if (hasCmp && iSku !== -1 && String(r[iSku] || '').trim() !== '') blankWithFallbackKey++;
    var key = fcEvtUp_(iCmp !== -1 ? r[iCmp] : '') + '|' + fcEvtUp_(hasLine ? r[iLine] : '') + '|' +
      fcEvtUp_(iMkId !== -1 ? r[iMkId] : '') + '|' + fcEvtUp_(iSku !== -1 ? r[iSku] : '') + '|' +
      fcEvtUp_(iMonth !== -1 ? r[iMonth] : '') + '|' + fcEvtUp_(iYear !== -1 ? r[iYear] : '');
    if (keySeen[key]) dupKeys++; else keySeen[key] = 1;
  }
  return jsonResponse_({ success: true, data: {
    total_rows: total, blank_event_fc_id: blank,
    blank_reidentifiable_by_campaign_line: blankWithLineKey,
    blank_reidentifiable_by_fallback_key: blankWithFallbackKey,
    blank_with_duplicate_business_key: dupKeys,
    has_legacy_event_id_column: hasLegacyEventIdCol,
    note: 'READ-ONLY audit — no data written. Backfill is a separate manual action (backfillFcSpecialEventIds).'
  } });
}

/**
 * ONE-TIME manual backfill of blank `event_fc_id` — standalone, re-runnable, DRY-RUN FIRST. NOT wired
 * to any auto path. Body:
 *   { }                → DRY-RUN (default): reports would_fill / skipped_no_campaign (ambiguous) /
 *                        duplicate_business_key (collision) / sample — writes NOTHING.
 *   { confirm: true }  → EXECUTE: assigns a fresh EFC-id to each blank-id row that has a campaign_id;
 *                        rows without a campaign_id are skipped (ambiguous / not safely identifiable).
 * Idempotent / re-runnable: a row that already has an id is always skipped. Collision = multiple blank
 * rows sharing the same business key (each still gets its own distinct new id, but is reported).
 */
function handleBackfillFcSpecialEventIds_(body) {
  var dryRun = !(body && body.confirm === true);
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName('fc_special_events');
  if (!sheet) return jsonResponse_({ success: false, error: 'fc_special_events sheet not found' });
  fcWriteEnsureColumns_(sheet, FC_SPECIAL_EVENTS_HEADERS_);
  var s = fcWriteReadSheet_(sheet);
  var iId = s.col('event_fc_id'), iCmp = s.col('campaign_id'), iLine = s.col('campaign_sku_line_id'),
      iMkId = s.col('marketplace_id'), iSku = s.col('sku'), iMonth = s.col('event_month'), iYear = s.col('year');
  if (iId === -1) return jsonResponse_({ success: false, error: 'event_fc_id column missing' });

  // Pass 1 — plan: identify fillable rows, ambiguous rows, and colliding business keys.
  var fillable = [], skippedNoCampaign = 0, keyCount = {}, sample = [];
  for (var i = 1; i < s.rows.length; i++) {
    var r = s.rows[i];
    if (r.join('') === '') continue;
    if (String(r[iId] || '').trim() !== '') continue;                       // already has id → skip (re-runnable)
    if (iCmp === -1 || String(r[iCmp] || '').trim() === '') { skippedNoCampaign++; continue; }   // ambiguous
    var key = fcEvtUp_(r[iCmp]) + '|' + fcEvtUp_(iLine !== -1 ? r[iLine] : '') + '|' +
      fcEvtUp_(iMkId !== -1 ? r[iMkId] : '') + '|' + fcEvtUp_(iSku !== -1 ? r[iSku] : '') + '|' +
      fcEvtUp_(iMonth !== -1 ? r[iMonth] : '') + '|' + fcEvtUp_(iYear !== -1 ? r[iYear] : '');
    keyCount[key] = (keyCount[key] || 0) + 1;
    fillable.push({ row: i + 1, key: key });
    if (sample.length < 10) sample.push({ row: i + 1, sku: iSku !== -1 ? r[iSku] : '', campaign_id: r[iCmp] });
  }
  var collisions = fillable.filter(function (f) { return keyCount[f.key] > 1; }).length;

  if (dryRun) {
    return jsonResponse_({ success: true, data: {
      mode: 'dry_run', would_fill: fillable.length, skipped_no_campaign_id: skippedNoCampaign,
      collision_duplicate_business_key: collisions, sample: sample,
      note: 'DRY-RUN — nothing written. Re-run with { confirm: true } to execute. Ambiguous rows (no campaign_id) are never auto-filled; colliding rows each get a distinct new EFC- id.'
    } });
  }

  // Pass 2 — execute (each fillable row gets a distinct new id).
  var filled = 0;
  for (var k = 0; k < fillable.length; k++) {
    sheet.getRange(fillable[k].row, iId + 1).setValue('EFC-' + Utilities.getUuid().substring(0, 12).toUpperCase());
    filled++;
  }
  return jsonResponse_({ success: true, data: {
    mode: 'executed', backfilled: filled, skipped_no_campaign_id: skippedNoCampaign,
    collision_duplicate_business_key: collisions
  } });
}

// ---- fc_target_rules ----

/**
 * Create/update a target % rule. Body: { target_rule_id?, company?, country?, marketplace?, scope_type,
 * scope_id, year?, category?, series?, sku?, target_percentage?, jan_pct..dec_pct, note?, actor? }
 */
function handleUpsertFcTargetRule_(body) {
  body = body || {};
  var actor = String(body.updated_by || body.actor || 'fc-summary').trim();
  if (!String(body.scope_type || '').trim()) {
    return jsonResponse_({ success: false, error: 'Missing scope_type for target rule' });
  }
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var result;
  try {
    result = fcWriteUpsert_(ss, 'fc_target_rules', FC_TARGET_RULES_HEADERS_, 'target_rule_id',
      String(body.target_rule_id || '').trim(), body, actor);
  } catch (e) {
    return jsonResponse_({ success: false, error: String(e && e.message ? e.message : e) });
  }
  return jsonResponse_({ success: true, data: result });
}

/** Delete a target rule by target_rule_id. Body: { target_rule_id }. */
function handleDeleteFcTargetRule_(body) {
  var id = String((body && body.target_rule_id) || '').trim();
  if (!id) return jsonResponse_({ success: false, error: 'Missing target_rule_id' });
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  return jsonResponse_({ success: true, data: fcWriteDelete_(ss, 'fc_target_rules', 'target_rule_id', id) });
}
